#@ load("@ytt:data", "data")

#@ def labels():
primes-dev: ""
#@ end

---
apiVersion: v1
kind: Service
metadata:
  namespace: apps
  name: primes-dev
spec:
  ports:
  - port: #@ data.values.svc_port
    targetPort: #@ data.values.app_port
  selector: #@ labels()
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apps
  name: primes-dev
spec:
  selector:
    matchLabels: #@ labels()
  template:
    metadata:
      labels: #@ labels()
    spec:
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: primes-dev
        image: harbor.lab.zoolabs.me/apps/primes@sha256:061ac41e98cff9c90f9e6bd8d34b5666c3f2f91fe4bb6196d1855d702e49cdaf
        env:
        - name: WAVEFRONT_APPLICATION_NAME
          value: primes-dev
        - name: WAVEFRONT_APPLICATION_SERVICE
          value: primes
        - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI
          value: #@ data.values.wavefront_proxy_url
