#@ load("@ytt:data", "data")

#@ def labels():
console-availability-client: ""
app: "console-availability"
service: console-availability-client
#@ end

---
apiVersion: v1
kind: Service
metadata:
  namespace: #@ data.values.namespace
  name: console-availability-client
spec:
  ports:
  - port: #@ data.values.svc_port
    protocol: TCP
    targetPort: #@ data.values.app_port
    name: http-console-availability-client
  selector: #@ labels()
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: #@ data.values.namespace
  name: console-availability-client
  labels: #@ labels()
spec:
  selector:
    matchLabels: #@ labels()
  template:
    metadata:
      labels: #@ labels()
    spec:
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: console-availability-client
        image: harbor.lab.zoolabs.me/apps/client@sha256:324a3b0c69237067eac38abbe2c632f83afb3044f5ed6efd83d00caf5bf9ada5
        imagePullPolicy: Always
        resources:
          limits:
            memory: 1Gi
        ports:
          - containerPort: 8080
            name: http-console-availability-client
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health
          initialDelaySeconds: 60
          periodSeconds: 2
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health
          initialDelaySeconds: 15
        env:
        - name: WAVEFRONT_APPLICATION_NAME
          value: console-availability
        - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI
          value: #@ data.values.wavefront_proxy_url
        - name: CONSOLE_SERVER_HOSTNAME
          value: #@ data.values.console_server_hostname
        - name: CONSOLE_SERVER_PORT
          value: #@ data.values.console_server_port
