#@ load("@ytt:data", "data")

#@ def labels():
console-availability-server: ""
#@ end

---
apiVersion: v1
kind: Service
metadata:
  namespace: #@ data.values.namespace
  name: console-availability-server
spec:
  ports:
  - port: #@ data.values.svc_port
    targetPort: #@ data.values.app_port
  selector: #@ labels()
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: #@ data.values.namespace
  name: console-availability-server
spec:
  selector:
    matchLabels: #@ labels()
  template:
    metadata:
      labels: #@ labels()
    spec:
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: console-availability-server
        image: harbor.lab.zoolabs.me/apps/server@sha256:b18b2b7866d7bf1b45c9e9c9cc511c9b3277cc2827222ed152cef25112d2ce94
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 1Gi
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health
          initialDelaySeconds: 60
          periodSeconds: 2
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health
          initialDelaySeconds: 15
        env:
        - name: WAVEFRONT_APPLICATION_NAME
          value: console-availability-server
        - name: WAVEFRONT_APPLICATION_SERVICE
          value: console-availability
        - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI
          value: #@ data.values.wavefront_proxy_url
