#@ load("@ytt:data", "data")

#@ def labels():
console-availability-service: ""
app: "console-availability"
service: console-availability-service
#@ end

---
apiVersion: v1
kind: Service
metadata:
  namespace: #@ data.values.namespace
  name: console-availability-service
spec:
  ports:
  - port: #@ data.values.svc_port
    targetPort: #@ data.values.app_port
    name: http-ca-service
  selector: #@ labels()
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: #@ data.values.namespace
  name: console-availability-service
  labels: #@ labels()
spec:
  selector:
    matchLabels: #@ labels()
  template:
    metadata:
      labels: #@ labels()
    spec:
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: console-availability-service
        image: harbor.lab.zoolabs.me/apps/server@sha256:5e71ab5f611763288e26b2a72829c62066b2b181953713c341cf78cb46b0784e
        imagePullPolicy: Always
        resources:
          limits:
            memory: 1Gi
        ports:
          - containerPort: 8080
            name: http-ca-service
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health
          initialDelaySeconds: 60
          periodSeconds: 2
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health
          initialDelaySeconds: 15
        env:
        - name: WAVEFRONT_APPLICATION_NAME
          value: console-availability
        - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI
          value: #@ data.values.wavefront_proxy_url
